[package]
name = "getpanics"
version = "0.0.0"
edition = "2021"

[dependencies]
ra_ap_ide = "0.0.210"
ra_ap_load-cargo = "0.0.210"
ra_ap_paths = "0.0.210"
ra_ap_project_model = "0.0.210"
ra_ap_syntax = "0.0.210"
ra_ap_vfs = "0.0.210"
